import type { Recipe } from "./types";

/**
 * Bundled starter recipes. This ships inside the static export so the app
 * has content on first load with zero network requests, then gets copied
 * into IndexedDB (see db.ts) so the user can edit/add recipes offline.
 *
 * All recipes are vegan — no meat, fish, dairy, eggs, or honey. See
 * AGENTS.md's "Adding or editing recipes" section before adding more.
 */
export const seedRecipes: Recipe[] = [
  {
    id: "creamy-tomato-pasta",
    title: "Creamy Tomato Pasta",
    description: "A weeknight pasta with a rich, dairy-free tomato sauce.",
    emoji: "🍝",
    tags: ["dinner", "vegan", "pasta"],
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    ingredients: [
      { text: "400 g pasta (rigatoni or penne)" },
      { text: "2 tbsp olive oil" },
      { text: "1 small onion, finely chopped" },
      { text: "3 cloves garlic, minced" },
      { text: "700 g crushed tomatoes" },
      { text: "150 ml full-fat coconut milk" },
      { text: "3 tbsp nutritional yeast" },
      { text: "Salt and pepper" },
      { text: "Fresh basil, torn" },
    ],
    steps: [
      { order: 1, instruction: "Bring a large pot of salted water to a boil." },
      { order: 2, instruction: "Add the pasta and cook until al dente.", timerMinutes: 10 },
      { order: 3, instruction: "Meanwhile, heat the olive oil in a large pan over medium heat." },
      { order: 4, instruction: "Add the onion and cook until soft.", timerMinutes: 5 },
      { order: 5, instruction: "Add the garlic and cook until fragrant, about 30 seconds." },
      { order: 6, instruction: "Pour in the crushed tomatoes, season with salt and pepper, and simmer.", timerMinutes: 10 },
      { order: 7, instruction: "Stir in the coconut milk and nutritional yeast until the sauce is smooth." },
      { order: 8, instruction: "Drain the pasta and toss it into the sauce until fully coated." },
      { order: 9, instruction: "Top with fresh basil and serve immediately." },
    ],
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "morning-oat-porridge",
    title: "Morning Oat Porridge",
    description: "Warm, simple, and endlessly customizable.",
    emoji: "🥣",
    tags: ["breakfast", "vegan", "quick"],
    servings: 2,
    prepMinutes: 2,
    cookMinutes: 8,
    ingredients: [
      { text: "1 cup rolled oats" },
      { text: "2 cups oat milk (or other plant milk), or water" },
      { text: "Pinch of salt" },
      { text: "1 tbsp maple syrup" },
      { text: "Toppings: banana, berries, nuts" },
    ],
    steps: [
      { order: 1, instruction: "Combine the oats, plant milk, and salt in a saucepan over medium heat." },
      { order: 2, instruction: "Cook, stirring occasionally, until thickened.", timerMinutes: 8 },
      { order: 3, instruction: "Remove from heat and stir in the maple syrup." },
      { order: 4, instruction: "Spoon into bowls and add your toppings." },
    ],
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "red-lentil-dal",
    title: "Red Lentil Dal",
    description: "A quick, everyday dal simmered with turmeric, cumin, and ginger.",
    emoji: "🍛",
    tags: ["dinner", "vegan", "indian", "dal"],
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    ingredients: [
      { text: "1 cup (200 g) red lentils, rinsed" },
      { text: "1 tbsp coconut oil" },
      { text: "1 tsp cumin seeds" },
      { text: "1 onion, finely chopped" },
      { text: "3 cloves garlic, minced" },
      { text: "1 tbsp fresh ginger, grated" },
      { text: "1 tsp ground turmeric" },
      { text: "1 tsp ground coriander" },
      { text: "400 g canned chopped tomatoes" },
      { text: "700 ml water or vegetable stock" },
      { text: "Salt, to taste" },
      { text: "Fresh cilantro, chopped, to serve" },
    ],
    steps: [
      { order: 1, instruction: "Rinse the lentils in cold water until it runs clear." },
      { order: 2, instruction: "Heat the coconut oil in a large pot over medium heat." },
      { order: 3, instruction: "Add the cumin seeds and let them sizzle for 30 seconds." },
      { order: 4, instruction: "Add the onion and cook until soft and golden.", timerMinutes: 5 },
      { order: 5, instruction: "Stir in the garlic and ginger and cook for 1 minute." },
      { order: 6, instruction: "Add the turmeric and coriander and stir for 30 seconds." },
      { order: 7, instruction: "Add the tomatoes and lentils to the pot." },
      { order: 8, instruction: "Pour in the water and bring to a boil." },
      { order: 9, instruction: "Reduce the heat and simmer until the lentils are soft.", timerMinutes: 20 },
      { order: 10, instruction: "Season with salt and serve topped with fresh cilantro." },
    ],
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "yellow-split-pea-dal-ginger",
    title: "Yellow Split Pea Dal with Ginger",
    description: "A warming split pea dal brightened with plenty of fresh ginger.",
    emoji: "🫘",
    tags: ["dinner", "vegan", "indian", "dal"],
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 40,
    ingredients: [
      { text: "1 cup (200 g) yellow split peas, rinsed" },
      { text: "1 tbsp coconut oil" },
      { text: "1 tsp black mustard seeds" },
      { text: "1 tsp cumin seeds" },
      { text: "1 onion, finely chopped" },
      { text: "2 tbsp fresh ginger, grated" },
      { text: "3 cloves garlic, minced" },
      { text: "1 tsp ground turmeric" },
      { text: "1/2 tsp chili powder (optional)" },
      { text: "950 ml water or vegetable stock" },
      { text: "Salt, to taste" },
      { text: "Juice of 1/2 lemon" },
    ],
    steps: [
      { order: 1, instruction: "Rinse the split peas in cold water." },
      { order: 2, instruction: "Heat the coconut oil in a large pot over medium heat." },
      { order: 3, instruction: "Add the mustard seeds and cumin seeds and cook until they start to pop." },
      { order: 4, instruction: "Add the onion and cook until soft.", timerMinutes: 5 },
      { order: 5, instruction: "Stir in the ginger and garlic and cook for 1 minute." },
      { order: 6, instruction: "Add the turmeric and chili powder and stir briefly." },
      { order: 7, instruction: "Add the split peas and water to the pot." },
      { order: 8, instruction: "Bring to a boil, then reduce the heat and cover." },
      { order: 9, instruction: "Simmer until the split peas are soft and creamy.", timerMinutes: 35 },
      { order: 10, instruction: "Season with salt and stir in the lemon juice before serving." },
    ],
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "coconut-spinach-dal",
    title: "Coconut Spinach Dal",
    description: "Creamy coconut dal folded with fresh spinach.",
    emoji: "🥥",
    tags: ["dinner", "vegan", "indian", "dal"],
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    ingredients: [
      { text: "1 cup (200 g) red lentils, rinsed" },
      { text: "1 tbsp coconut oil" },
      { text: "1 tsp cumin seeds" },
      { text: "1 onion, finely chopped" },
      { text: "3 cloves garlic, minced" },
      { text: "1 tbsp fresh ginger, grated" },
      { text: "1 tsp ground turmeric" },
      { text: "1 tsp garam masala" },
      { text: "400 ml canned coconut milk" },
      { text: "475 ml water" },
      { text: "4 cups (120 g) fresh spinach, roughly chopped" },
      { text: "Salt, to taste" },
    ],
    steps: [
      { order: 1, instruction: "Rinse the lentils in cold water until it runs clear." },
      { order: 2, instruction: "Heat the coconut oil in a large pot over medium heat." },
      { order: 3, instruction: "Add the cumin seeds and let them sizzle for 30 seconds." },
      { order: 4, instruction: "Add the onion and cook until soft.", timerMinutes: 5 },
      { order: 5, instruction: "Stir in the garlic and ginger and cook for 1 minute." },
      { order: 6, instruction: "Add the turmeric and garam masala and stir briefly." },
      { order: 7, instruction: "Add the lentils, coconut milk, and water to the pot." },
      { order: 8, instruction: "Bring to a boil, then reduce the heat and simmer until the lentils are soft.", timerMinutes: 20 },
      { order: 9, instruction: "Stir in the spinach and cook until wilted." },
      { order: 10, instruction: "Season with salt and serve." },
    ],
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];
