import { resolveUserIdForToken } from "../lib/personal-access-tokens-db";

/**
 * Auth abstraction for the Simmer MCP server. Every repository/service call
 * downstream takes a `userId` from a `McpRequestContext` resolved here — see
 * docs/mcp.md's "Authentication" section for the full picture.
 *
 * Real accounts back this now: a bearer token is a personal access token
 * (src/lib/personal-access-tokens-db.ts), generated by a signed-in user
 * from the account settings page (src/app/settings/) and hashed at rest —
 * this file never sees or logs the raw token itself. The only remaining
 * dev convenience is the no-`Authorization`-header fallback below, which
 * is hard-disabled outside development so it can never work in production.
 *
 * PRODUCTION TODO: this is deliberately personal-access-token auth, not
 * full OAuth 2.1 — see docs/mcp.md's "Production TODO" section for what a
 * hosted "Sign in to Simmer" connector flow for Claude/ChatGPT would add
 * on top of this (authorization + token endpoints, dynamic client
 * registration, consent screen). Nothing downstream needs to change for
 * that upgrade: every service and repository already takes userId as an
 * opaque, already-authenticated value.
 */
export interface McpRequestContext {
  userId: string;
}

export class UnauthorizedError extends Error {
  constructor(message = "Missing or invalid Simmer credentials.") {
    super(message);
    this.name = "UnauthorizedError";
  }
}

const DEFAULT_DEV_USER_ID = "dev-user";

export type HeaderBag = Record<string, string | string[] | undefined>;

/**
 * Resolves the calling user from an `Authorization: Bearer <token>` header
 * against the personal_access_token table. With no Authorization header at
 * all, falls back to SIMMER_MCP_DEV_USER_ID (default "dev-user") — but
 * only outside production, so a local client can connect with zero setup
 * without that ever becoming an open door in a real deployment.
 */
export async function resolveUserIdFromHeaders(headers: HeaderBag): Promise<McpRequestContext> {
  const authHeader = headers["authorization"] ?? headers["Authorization"];
  const value = Array.isArray(authHeader) ? authHeader[0] : authHeader;

  if (!value) {
    if (process.env.NODE_ENV !== "production") {
      return { userId: process.env.SIMMER_MCP_DEV_USER_ID || DEFAULT_DEV_USER_ID };
    }
    throw new UnauthorizedError("Missing Authorization header.");
  }

  const match = /^Bearer\s+(.+)$/i.exec(value.trim());
  if (!match) {
    throw new UnauthorizedError("Authorization header must be a Bearer token.");
  }

  const userId = await resolveUserIdForToken(match[1] ?? "");
  if (!userId) {
    throw new UnauthorizedError("Unknown or revoked Simmer access token.");
  }
  return { userId };
}

/** stdio is local-dev only — resolve directly from env, no token lookup. */
export function resolveUserIdForStdio(): McpRequestContext {
  return { userId: process.env.SIMMER_MCP_DEV_USER_ID || DEFAULT_DEV_USER_ID };
}
